# https://fabricmc.net/develop/

[versions]

# Minecraft / Loaders
minecraft = "1.20.1"
fabric-loader = "0.14.21"
fabric-api = "0.86.1+1.20.1"
fabric-loom = "1.3-SNAPSHOT"

# Dependencies
jsr305 = "3.0.2"

# Mod dependencies
modmenu = "7.2.1"
cloth-config = "11.1.106"

# Tests
junit = "4.13.1"


[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

findbugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
cloth-config = { group = "me.shedaniel.cloth", name = "cloth-config-fabric", version.ref = "cloth-config" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]

[plugins]
loom = { id = "fabric-loom", version.ref = "fabric-loom" }
