name: Gradle CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  name: Gradle-Build
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      
      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          java-version: 17
          distribution: 'zulu'

      # Build with Gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@c295a4096e1d2c453eaf1f65c6f96686e26bd8be
        with:
          arguments: build

      # Test with Gradle
      - name: Test with Gradle
        uses: gradle/gradle-build-action@c295a4096e1d2c453eaf1f65c6f96686e26bd8be
        with:
          arguments: test
